project.version=4.3.0+26.2
project.java=25
project.build-java=25
project.minecraft=26.2
project.enabled-loaders=fabric,forge,neoforge
dependencies.liteminer=4.1.2+26.2
dependencies.modonomicon-fabric=VI4rtcu3
dependencies.modonomicon-forge=MmWUb6Ec
dependencies.modonomicon-neoforge=Dp6Y7m5f

mod.minecraft-range=>=26.2
mod.fabric-range=>=26.2
mod.forge-loader-range=[65,)
mod.neoforge-loader-range=[4,)

publish.game-versions=26.2
dependencies.modrinth.required=amber,konfig
dependencies.curseforge.required=amber-lib,konfig
dependencies.modrinth.optional=liteminer,modonomicon
dependencies.curseforge.optional=liteminer,modonomicon
